### ISSUE TITLE
How to transfer out

### ISSUE THREAD

**Issue by ahoslc** [AndreMiras/EtherollApp#105]
Since the app no longer works how can I send my money out of the wallet since I have no pass phrase?

**Comment by AndreMiras** [comment]
Hi @ahoslc thanks for reaching out to me.
Yes I didn't make a new release after the contract update, but the code is ready but I wanted to fix https://github.com/AndreMiras/EtherollApp/issues/103 first.
Anyway I will make a quick silent release for you now.

Regarding how to transfer founds, you can access the keystore on device and load it with any other wallet application. So you can use a file browser on your device and then copy the `*.json` files.
I also have a ticket to make it less cumbersome https://github.com/AndreMiras/EtherollApp/issues/95 but didn't get a chance to tackle.
If you struggle let me know and I can help in a direct chat.

In the meantime I'll do a partial release that includes some early/draft notification system.

**Comment by ahoslc** [comment]
I appreciate just let me know and I can snag the Android apk

**Comment by AndreMiras** [comment]
Just ended it here it is https://github.com/AndreMiras/EtherollApp/releases/download/v20180911/etheroll-2018.0911-debug.apk :smile: 
It's quite an easy change, is just that I wanted to have more feature for not spamming Reddit with a release that just brings the smart contract address update.
In fact my bad, I should have silently released in GitHub at least without necessarily notifying Reddit.
Have fun testing it and le met know how it goes.
I still want to keep that ticket open nonetheless because it's a reminder for me to either document the way to transfer out or implement a more seamless export feature.
